FROM quay.io/projectquay/golang:1.24 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o gpu-allocator ./cmd/gpu-allocator

# has nvidia-smi
FROM nvcr.io/nvidia/cuda:12.8.0-base-ubuntu22.04

WORKDIR /app
COPY --from=builder /app/gpu-allocator .

EXPOSE 8080

ENTRYPOINT ["/app/gpu-allocator"]
