#!/usr/bin/env python3
# Copyright 2025 The llm-d Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# 	http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""
vLLM Launcher
"""

import logging
import multiprocessing
import os
import re
import signal
import sys
import uuid
from contextlib import asynccontextmanager
from http import HTTPStatus  # HTTP Status Codes
from typing import Dict, List, Optional

import uvloop
from fastapi import FastAPI, Header, HTTPException, Path
from fastapi.responses import JSONResponse, Response
from gputranslator import GpuTranslator
from pydantic import BaseModel
from vllm.entrypoints.openai.api_server import run_server
from vllm.entrypoints.openai.cli_args import make_arg_parser, validate_parsed_serve_args
from vllm.entrypoints.utils import cli_env_setup
from vllm.utils.argparse_utils import FlexibleArgumentParser

MAX_LOG_RESPONSE_BYTES = 1 * 1024 * 1024  # 1 MB default for API response


class LogRangeNotAvailable(Exception):
    """Raised when the requested start_byte is beyond available log content"""

    def __init__(self, start_byte, available_bytes):
        self.start_byte = start_byte
        self.available_bytes = available_bytes
        super().__init__(
            f"start_byte {start_byte} is beyond available content "
            f"({available_bytes} bytes available)"
        )


# Define a the expected JSON structure in dataclass
class VllmConfig(BaseModel):
    options: str
    gpu_uuids: Optional[List[str]] = None
    env_vars: Optional[Dict[str, str]] = None


class VllmInstance:
    """Represents a single vLLM instance"""

    def __init__(
        self,
        instance_id: str,
        config: VllmConfig,
        gpu_translator: GpuTranslator,
        log_dir: str = "",
    ):
        """
        Initialize VllmInstance object
        :param instance_id: Instance id (autogenerated or custom)
        :param config: VllmConfig object
        :param gpu_translator: GpuTranslator object
        :param log_dir: Directory for log files (defaults to /tmp)
        """

        # Check for CUDA device UUIDs and set CUDA_VISIBLE_DEVICES accordingly
        if config.gpu_uuids:
            cuda_indices = []
            for uuid_str in config.gpu_uuids:
                index = gpu_translator.uuid_to_index(uuid_str)
                cuda_indices.append(str(index))
            logger.info(
                f"Translated GPU UUIDs {config.gpu_uuids} to indices {cuda_indices}."
            )

            if config.env_vars is None:
                config.env_vars = {}
            config.env_vars["CUDA_VISIBLE_DEVICES"] = ",".join(cuda_indices)
            logger.info(
                f"Set CUDA_VISIBLE_DEVICES to \
                    {config.env_vars['CUDA_VISIBLE_DEVICES']} based on UUIDs."
            )

        # Initialize instance variables
        self.instance_id = instance_id
        self.config = config
        self.process: Optional[multiprocessing.Process] = None
        self._log_file_path = os.path.join(
            log_dir or "/tmp",
            f"launcher-{os.getpid()}-vllm-{instance_id}.log",
        )

    def start(self) -> dict:
        """
        Start this vLLM instance
        :return: Status of the process.
        """
        if self.process and self.process.is_alive():
            return {"status": "already_running", "instance_id": self.instance_id}

        # Create empty log file before spawning the child process
        open(self._log_file_path, "wb").close()

        self.process = multiprocessing.Process(
            target=vllm_kickoff, args=(self.config, self._log_file_path)
        )
        self.process.start()

        return {
            "status": "started",
            "instance_id": self.instance_id,
        }

    def stop(self, timeout: int = 10) -> dict:
        """
        Stop existing vLLM instance
        :param timeout: waits for the process to stop, defaults to 10
        :return: a dictionary with the status "terminated"
        """
        if not self.process or not self.process.is_alive():
            self._cleanup_log_file()
            return {
                "status": "not_running",
                "instance_id": self.instance_id,
            }

        # Graceful termination — send SIGTERM to the vLLM process,
        # which will propagate shutdown to the EngineCore via vLLM's
        # own cleanup logic.
        self.process.terminate()
        self.process.join(timeout=timeout)

        # Force kill the entire process group (vLLM server + EngineCore)
        # if graceful shutdown did not complete in time.
        if self.process.is_alive():
            try:
                os.killpg(self.process.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
            self.process.join()

        self._cleanup_log_file()
        return {
            "status": "terminated",
            "instance_id": self.instance_id,
        }

    def _cleanup_log_file(self):
        """Remove the log file if it exists."""
        try:
            os.unlink(self._log_file_path)
        except FileNotFoundError:
            pass

    def get_status(self) -> dict:
        """
        Returns the status of the process
        :return: Status of the running process.
        """

        return {
            "status": "running" if self.process.is_alive() else "stopped",
            "instance_id": self.instance_id,
        }

    def get_log_bytes(
        self, start: int = 0, end: int | None = None
    ) -> tuple[bytes, int]:
        """
        Retrieve log bytes from the child process.
        :param start: First byte to read (inclusive, 0-based).
        :param end: Last byte to read (inclusive, must be >= start).
                    None means up to start + MAX_LOG_RESPONSE_BYTES - 1
                    or EOF, whichever comes first.
        :return: (content_bytes, current_total_log_length)
        :raises LogRangeNotAvailable: If start is beyond available content
        """
        try:
            total = os.path.getsize(self._log_file_path)
        except FileNotFoundError:
            total = 0

        if start >= total:
            raise LogRangeNotAvailable(start, total)

        if end is None:
            read_end = min(start + MAX_LOG_RESPONSE_BYTES - 1, total - 1)
        else:
            read_end = min(end, total - 1)

        nbytes = read_end - start + 1
        with open(self._log_file_path, "rb") as f:
            f.seek(start)
            data = f.read(nbytes)
        return (data, total)


# Multi-instance vLLM process manager
class VllmMultiProcessManager:
    def __init__(
        self,
        mock_gpus: bool = False,
        mock_gpu_count: int = 8,
        node_name: Optional[str] = None,
        namespace: Optional[str] = None,
        log_dir: str = "",
    ):
        self.instances: Dict[str, VllmInstance] = {}
        self.gpu_translator = GpuTranslator(
            mock_gpus=mock_gpus,
            node_name=node_name,
            namespace=namespace,
            mock_gpu_count=mock_gpu_count,
        )
        self.log_dir = log_dir

    def create_instance(
        self, vllm_config: VllmConfig, instance_id: Optional[str] = None
    ) -> dict:
        """Create and start a new vLLM instance"""
        if instance_id is None:
            instance_id = str(uuid.uuid4())

        if instance_id in self.instances:
            raise ValueError(f"Instance with ID {instance_id} already exists")

        instance = VllmInstance(
            instance_id, vllm_config, self.gpu_translator, self.log_dir
        )
        self.instances[instance_id] = instance

        return instance.start()

    def stop_instance(self, instance_id: str, timeout: int = 10) -> dict:
        """Stop a specific vLLM instance"""
        if instance_id not in self.instances:
            raise KeyError(f"Instance {instance_id} not found")

        result = self.instances[instance_id].stop(timeout)

        # Clean up stopped instance
        if result["status"] in ["terminated", "not_running"]:
            del self.instances[instance_id]

        return result

    def stop_all_instances(self, timeout: int = 10) -> dict:
        """Stop all running vLLM instances"""
        results = []
        instance_ids = list(self.instances.keys())

        for instance_id in instance_ids:
            try:
                result = self.stop_instance(instance_id, timeout)
                results.append(result)
            except KeyError:
                continue  # Instance was already removed

        return {
            "status": "all_stopped",
            "stopped_instances": results,
            "total_stopped": len(results),
        }

    def get_instance_status(self, instance_id: str) -> dict:
        """Get status of a specific instance"""
        if instance_id not in self.instances:
            raise KeyError(f"Instance {instance_id} not found")

        return self.instances[instance_id].get_status()

    def get_all_instances_status(self) -> dict:
        """Get status of all instances"""
        instances_status = []
        running_count = 0

        for instance in self.instances.values():
            status = instance.get_status()
            instances_status.append(status)
            if status["status"] == "running":
                running_count += 1

        return {
            "total_instances": len(self.instances),
            "running_instances": running_count,
            "instances": instances_status,
        }

    def list_instances(self) -> List[str]:
        """List all instance IDs"""
        return list(self.instances.keys())

    def get_instance_log_bytes(
        self,
        instance_id: str,
        start: int = 0,
        end: int | None = None,
    ) -> tuple[bytes, int]:
        """
        Get log bytes from a specific instance.
        :param instance_id: ID of the instance
        :param start: First byte to read (inclusive, 0-based)
        :param end: Last byte to read (inclusive), or None for default limit
        :return: (content_bytes, total_file_size)
        :raises LogRangeNotAvailable: If start is beyond available content
        """
        if instance_id not in self.instances:
            raise KeyError(f"Instance {instance_id} not found")
        return self.instances[instance_id].get_log_bytes(start, end)


# Create global manager instance
vllm_manager = VllmMultiProcessManager()

# Setup logging
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(application: FastAPI):
    """Manage application lifecycle: clean up all vLLM instances on shutdown."""
    yield
    logger.info("Launcher shutting down, stopping all vLLM instances...")
    vllm_manager.stop_all_instances()


# Create FastAPI application
app = FastAPI(
    title="Multi-Instance vLLM Management API",
    version="2.0",
    description="REST API for managing multiple vLLM instances",
    lifespan=lifespan,
)


_RANGE_RE = re.compile(r"^bytes=(\d+)-(\d+)?$")


def parse_range_header(range_header: str) -> tuple[int, int | None]:
    """Parse an HTTP Range header value.

    Accepts ``bytes=START-END`` (both inclusive) or ``bytes=START-``
    (open-ended).  Returns ``(start, end)`` where *end* may be ``None``.

    Raises :class:`ValueError` for unsupported or malformed values
    (e.g. suffix ranges like ``bytes=-500``).
    """
    m = _RANGE_RE.match(range_header)
    if m is None:
        raise ValueError(f"Unsupported or malformed Range header: {range_header}")
    start = int(m.group(1))
    # group(2) is the end value; absent in open-ended ranges like "bytes=100-"
    end = int(m.group(2)) if m.group(2) else None
    if end is not None and end < start:
        raise ValueError(f"Range end ({end}) must be >= start ({start})")
    return (start, end)


############################################################
# Health Endpoint
############################################################
@app.get("/health")
async def health():
    """Health Status"""
    return JSONResponse(content={"status": "OK"}, status_code=HTTPStatus.OK)


######################################################################
# GET INDEX
######################################################################
@app.get("/")
async def index():
    """Root URL response"""
    return JSONResponse(
        content={
            "name": "Multi-Instance vLLM Management API",
            "version": "2.0",
            "endpoints": {
                "index": "GET /",
                "health": "GET /health",
                "create_instance": "POST /v2/vllm/instances",
                "create_named_instance": "PUT /v2/vllm/instances/{instance_id}",
                "delete_instance": "DELETE /v2/vllm/instances/{instance_id}",
                "delete_all_instances": "DELETE /v2/vllm/instances",
                "get_instance_status": "GET /v2/vllm/instances/{instance_id}",
                "get_all_instances": "GET /v2/vllm/instances",
                "get_instance_logs": "GET /v2/vllm/instances/{instance_id}/log",
            },
        },
        status_code=HTTPStatus.OK,
    )


######################################################################
# vLLM MANAGEMENT ENDPOINTS
######################################################################
@app.post("/v2/vllm/instances")
async def create_vllm_instance(vllm_config: VllmConfig):
    """Create a new vLLM instance with random instance ID"""

    try:
        result = vllm_manager.create_instance(vllm_config)
        return JSONResponse(content=result, status_code=HTTPStatus.CREATED)
    except Exception as e:
        logger.error(f"Failed to create vLLM instance: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.put("/v2/vllm/instances/{instance_id}")
async def create_id_vllm_instance(
    vllm_config: VllmConfig,
    instance_id: str = Path(..., description="Custom instance ID"),
):
    """Create a new vLLM instance with instance ID"""
    try:
        result = vllm_manager.create_instance(vllm_config, instance_id)
        return JSONResponse(content=result, status_code=HTTPStatus.CREATED)
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e))
    except Exception as e:
        logger.error(f"Failed to create vLLM instance {instance_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.delete("/v2/vllm/instances/{instance_id}")
async def delete_vllm_instance(
    instance_id: str = Path(..., description="Instance ID to delete")
):
    """Delete a specific vLLM instance"""
    try:
        result = vllm_manager.stop_instance(instance_id)
        return JSONResponse(content=result, status_code=HTTPStatus.OK)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"Instance {instance_id} not found")
    except Exception as e:
        logger.error(f"Failed to delete vLLM instance {instance_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.delete("/v2/vllm/instances")
async def delete_all_vllm_instances():
    """Delete all vLLM instances"""
    try:
        result = vllm_manager.stop_all_instances()
        return JSONResponse(content=result, status_code=HTTPStatus.OK)
    except Exception as e:
        logger.error(f"Failed to delete all vLLM instances: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/v2/vllm/instances")
async def get_all_vllm_instances(detail: bool = True):
    """
    Get information about all vLLM instances

    Query Parameters:
    - detail: If True (default), returns full status of all instances.
              If False, returns only instance IDs.
    """
    if detail:
        result = vllm_manager.get_all_instances_status()
    else:
        instances = vllm_manager.list_instances()
        result = {"instance_ids": instances, "count": len(instances)}

    return JSONResponse(content=result, status_code=HTTPStatus.OK)


@app.get("/v2/vllm/instances/{instance_id}")
async def get_vllm_instance_status(
    instance_id: str = Path(..., description="Instance ID")
):
    """Get status of a specific vLLM instance"""
    try:
        result = vllm_manager.get_instance_status(instance_id)
        return JSONResponse(content=result, status_code=HTTPStatus.OK)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"Instance {instance_id} not found")


@app.get("/v2/vllm/instances/{instance_id}/log")
async def get_vllm_instance_logs(
    instance_id: str = Path(..., description="Instance ID"),
    range: str | None = Header(None, alias="Range"),
):
    """
    Get logs from a specific vLLM instance.

    Supports range requests per RFC 9110 §14 (Range Requests).

    Without a Range header the full log (up to 1 MB) is returned with
    200 OK.  With ``Range: bytes=START-END`` or ``Range: bytes=START-``
    the requested slice is returned with 206 Partial Content.  In both
    cases the response includes a ``Content-Range`` header indicating the byte range
    and current total log length.
    """
    try:
        if range is None:
            start, end = 0, None
            partial = False
        else:
            try:
                start, end = parse_range_header(range)
            except ValueError as exc:
                raise HTTPException(status_code=400, detail=str(exc))
            partial = True

        data, total = vllm_manager.get_instance_log_bytes(instance_id, start, end)

        actual_end = start + len(data) - 1
        headers = {
            "Accept-Ranges": "bytes",
            "Content-Range": f"bytes {start}-{actual_end}/{total}",
        }
        if partial:
            status_code = HTTPStatus.PARTIAL_CONTENT
        else:
            status_code = HTTPStatus.OK

        return Response(
            content=data,
            status_code=status_code,
            media_type="application/octet-stream",
            headers=headers,
        )
    except KeyError:
        raise HTTPException(status_code=404, detail=f"Instance {instance_id} not found")
    except LogRangeNotAvailable as e:
        return Response(
            content=b"",
            status_code=HTTPStatus.REQUESTED_RANGE_NOT_SATISFIABLE,
            media_type="application/octet-stream",
            headers={"Content-Range": f"bytes */{e.available_bytes}"},
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to get logs for instance {instance_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


######################################################################
# HELPER FUNCTIONS
######################################################################


# Function to be executed by the child process
def vllm_kickoff(vllm_config: VllmConfig, log_file_path: str):
    """
    Child function to kickoff vllm instance
    :param vllm_config: vLLM configuration parameters and env variables
    :param log_file_path: Path to the log file for capturing stdout/stderr
    """

    # Isolate this process tree into its own process group so that
    # signals (SIGINT/SIGTERM) sent to the launcher's group do not
    # propagate to the vLLM server or its EngineCore child process.
    os.setpgrp()

    # Redirect stdout and stderr at the OS level using dup2 so that
    # all output (including from vLLM/uvicorn internal logging and any
    # C extensions writing to fd 1/2) is captured in the log file.
    log_fd = os.open(log_file_path, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o644)
    os.dup2(log_fd, sys.stdout.fileno())
    os.dup2(log_fd, sys.stderr.fileno())
    os.close(log_fd)
    sys.stdout = os.fdopen(1, "w")
    sys.stderr = os.fdopen(2, "w")

    logger.info(f"VLLM process (PID: {os.getpid()}) started.")
    # Set env vars in the current process
    if vllm_config.env_vars:
        set_env_vars(vllm_config.env_vars)

    # prepare args
    receive_args = vllm_config.options.split()

    cli_env_setup()
    parser = FlexibleArgumentParser(
        description="vLLM OpenAI-Compatible RESTful API server."
    )
    parser = make_arg_parser(parser)
    args = parser.parse_args(receive_args)
    validate_parsed_serve_args(args)

    uvloop.run(run_server(args))


# Function to set env variables
def set_env_vars(env_vars: Dict[str, str]):
    """
    Set environment variables from a dictionary
    :param env_vars: Dict with environment var name as keys and string values
    """

    # Set environment variables from a dictionary
    for key, value in env_vars.items():
        os.environ[key] = value


if __name__ == "__main__":
    import argparse

    import uvicorn

    parser = argparse.ArgumentParser(description="vLLM Launcher Service")
    parser.add_argument(
        "--mock-gpus",
        action="store_true",
        help="Enable mock GPU mode for CPU-only testing environments",
    )
    parser.add_argument(
        "--mock-gpu-count",
        type=int,
        default=8,
        help="Number of mock GPUs to create in mock mode (default: 8)",
    )
    parser.add_argument(
        "--host",
        type=str,
        default="0.0.0.0",
        help="Host to bind the server to (default: 0.0.0.0)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8001,
        help="Port to bind the server to (default: 8001)",
    )
    parser.add_argument(
        "--log-level",
        type=str,
        default="info",
        choices=["critical", "error", "warning", "info", "debug"],
        help="Logging level (default: info)",
    )

    args = parser.parse_args()

    # Configure root logger so launcher messages are visible before uvicorn
    logging.basicConfig(
        level=getattr(logging, args.log_level.upper()),
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    # Get node name from environment variable
    node_name = os.getenv("NODE_NAME")
    namespace = os.getenv("NAMESPACE")

    logger.info(
        "Launcher starting with args: mock_gpus=%s, mock_gpu_count=%d, "
        "host=%s, port=%d, log_level=%s, node_name=%s, namespace=%s",
        args.mock_gpus,
        args.mock_gpu_count,
        args.host,
        args.port,
        args.log_level,
        node_name,
        namespace,
    )

    # Reinitialize the global manager with mock mode settings
    vllm_manager = VllmMultiProcessManager(
        mock_gpus=args.mock_gpus,
        mock_gpu_count=args.mock_gpu_count,
        node_name=node_name,
        namespace=namespace,
    )

    uvicorn.run(app, host=args.host, port=args.port, log_level=args.log_level)
