# This more efficient and avoids https://gitlab.com/qemu-project/qemu/-/issues/2027
FROM --platform=$BUILDPLATFORM quay.io/projectquay/golang:1.25 AS builder
ARG TARGETOS
ARG TARGETARCH

RUN echo "I'm building for OS=$TARGETOS ARCH=$TARGETARCH"

# Install build tools
# The builder is based on UBI8, so we need epel-release-8.
RUN dnf install -y 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm' && \
    dnf install -y gcc-c++ libstdc++ libstdc++-devel clang zeromq-devel pkgconfig && \
    dnf clean all

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# Copy the go source
COPY cmd/ cmd/
COPY pkg/ pkg/

# Build
ENV CGO_ENABLED=0
ENV GOOS=${TARGETOS:-linux}
ENV GOARCH=${TARGETARCH}
ARG BUILD_REF
RUN go build -a -o bin/requester cmd/requester/main.go

FROM nvcr.io/nvidia/cuda:12.8.0-base-ubuntu22.04
WORKDIR /
COPY --from=builder /workspace/bin/requester /app/requester

ENTRYPOINT ["/app/requester"]
